apiVersion: v1
kind: Service

metadata:
  name: mongodb
  namespace: fullstack-platform

spec:
  clusterIP: None

  selector:
    app: mongodb

  ports:
    - port: 27017
      targetPort: 27017
      